version: '3.7'

services:

  ui:
    build:
      context: ./ui
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui/src:/app/src/delegated
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    image: pizza-api
    volumes:
      - ./api/dist:/app/dist
      - ./api/contracts:/app/contracts
      - ./api/package.json:/app/package.json
    ports:
      - 3001:3001
    depends_on:
      - truffle
      - api-watch
    environment:
      WEB3_PROVIDER: 'http://blockchain:8545'
      PORT: 3001
    command: npm run dev

  api-watch:
    image: pizza-api
    command: npm run watch
    volumes:
      - ./api/src:/app/src
      - ./api/dist:/app/dist
      - ./api/.babelrc:/app/.babelrc
    depends_on:
      - truffle

